categories:
  Sitekit:
  Sitekit.project:
    parent: Sitekit
  Sitekit.pages:
    parent: Sitekit
  Sitekit.templates:
    parent: Sitekit
  SocialMedia.settings:
    parent: Sitekit

settings:
  sitekit.project.companyName:
    category: Sitekit.project
    description: 'LLL:EXT:ot_sitekitbase/Configuration/Sets/Base/labels.xlf:settings.sitekit.project.companyName.description'
    type: string
    default: 'Company Name'

  sitekit.project.companyName2:
    category: Sitekit.project
    description: 'LLL:EXT:ot_sitekitbase/Configuration/Sets/Base/labels.xlf:settings.sitekit.project.companyName2.description'
    type: string
    default: ''

  sitekit.project.addressLine1:
    category: Sitekit.project
    description: 'LLL:EXT:ot_sitekitbase/Configuration/Sets/Base/labels.xlf:settings.sitekit.project.addressLine1.description'
    type: string
    default: ''

  sitekit.project.addressLine2:
    category: Sitekit.project
    description: 'LLL:EXT:ot_sitekitbase/Configuration/Sets/Base/labels.xlf:settings.sitekit.project.addressLine1.description'
    type: string
    default: ''

  sitekit.project.postalCode:
    category: Sitekit.project
    type: string
    default: ''

  sitekit.project.city:
    category: Sitekit.project
    type: string
    default: ''

  sitekit.project.telephone:
    category: Sitekit.project
    type: string
    default: ''

  sitekit.project.email:
    category: Sitekit.project
    type: string
    default: ''

  sitekit.pages.root:
    category: Sitekit.pages
    description: 'LLL:EXT:ot_sitekitbase/Configuration/Sets/Base/labels.xlf:settings.sitekit.pages.root.description'
    type: int
    default: 1

  sitekit.pages.footerNavigationRootPage:
    category: Sitekit.pages
    description: 'LLL:EXT:ot_sitekitbase/Configuration/Sets/Base/labels.xlf:settings.sitekit.pages.footerNavigationRootPage.description'
    type: int
    default: 0

  sitekit.pages.termsAndConditions:
    category: Sitekit.pages
    type: int
    default: 0

  sitekit.pages.legalNotice:
    category: Sitekit.pages
    type: int
    default: 0

  sitekit.pages.privacyPolicy:
    category: Sitekit.pages
    type: int
    default: 0

  sitekit.frameworks.frontend.directory:
    category: Sitekit.templates
    description: 'LLL:EXT:ot_sitekitbase/Configuration/Sets/Base/labels.xlf:settings.frameworks.frontend.directory.description'
    type: string
    default: 'Bootstrap5'

  sitekit.gutterSize:
    category: Sitekit.templates
    description: 'LLL:EXT:ot_sitekitbase/Configuration/Sets/Base/labels.xlf:settings.gutterSize.description'
    type: string
    default: 3
    enum:
      0: '0'
      1: '1'
      2: '2'
      3: '3'
      4: '4'
      5: '5'

  socialMedia.facebook.account:
    category: SocialMedia.settings
    type: string
    default: ''

  socialMedia.x.account:
    category: SocialMedia.settings
    type: string
    default: ''

  socialMedia.instagram.account:
    category: SocialMedia.settings
    type: string
    default: ''

  socialMedia.linkedIn.account:
    category: SocialMedia.settings
    type: string
    default: ''
