categories:
  Sitekit:
  Sitekit.project:
    parent: Sitekit
  Sitekit.project.brand:
    parent: Sitekit.project
  Sitekit.pages:
    parent: Sitekit
  Sitekit.templates:
    parent: Sitekit
  Sitekit.menus:
    parent: Sitekit
  Sitekit.menus.mainMenu:
    parent: Sitekit.menus
  Sitekit.menus.topMenu:
    parent: Sitekit.menus
  Sitekit.menus.languageMenu:
    parent: Sitekit.menus
  Sitekit.menus.subpagesMenu:
    parent: Sitekit.menus
  Sitekit.features:
    parent: Sitekit
  Sitekit.features.search:
    parent: Sitekit.features
  Sitekit.features.colorMode:
    parent: Sitekit.features
  SocialMedia.settings:
    parent: Sitekit
  Sitekit.contentElements:
    parent: Sitekit

settings:
  sitekit.project.companyName:
    category: Sitekit.project
    description: 'LLL:EXT:ot_sitekitbase/Configuration/Sets/Base/labels.xlf:settings.sitekit.project.companyName.description'
    type: string
    default: 'Company Name'

  sitekit.project.companyName2:
    category: Sitekit.project
    description: 'LLL:EXT:ot_sitekitbase/Configuration/Sets/Base/labels.xlf:settings.sitekit.project.companyName2.description'
    type: string
    default: ''

  sitekit.project.addressLine1:
    category: Sitekit.project
    description: 'LLL:EXT:ot_sitekitbase/Configuration/Sets/Base/labels.xlf:settings.sitekit.project.addressLine1.description'
    type: string
    default: ''

  sitekit.project.addressLine2:
    category: Sitekit.project
    description: 'LLL:EXT:ot_sitekitbase/Configuration/Sets/Base/labels.xlf:settings.sitekit.project.addressLine2.description'
    type: string
    default: ''

  sitekit.project.postalCode:
    category: Sitekit.project
    type: string
    default: ''

  sitekit.project.city:
    category: Sitekit.project
    type: string
    default: ''

  sitekit.project.telephone:
    category: Sitekit.project
    type: string
    default: ''

  sitekit.project.email:
    category: Sitekit.project
    type: string
    default: ''

  sitekit.project.brand.logo.file.svg:
    category: Sitekit.project.brand
    description: 'LLL:EXT:ot_sitekitbase/Configuration/Sets/Base/labels.xlf:settings.sitekit.project.brand.logo.file.svg.description'
    type: string
    default: 'EXT:ot_sitekitbase/Resources/Public/Icons/Extension.svg'


  sitekit.pages.root:
    category: Sitekit.pages
    description: 'LLL:EXT:ot_sitekitbase/Configuration/Sets/Base/labels.xlf:settings.sitekit.pages.root.description'
    type: page
    default: 1

  sitekit.pages.footerNavigationRootPage:
    category: Sitekit.pages
    description: 'LLL:EXT:ot_sitekitbase/Configuration/Sets/Base/labels.xlf:settings.sitekit.pages.footerNavigationRootPage.description'
    type: page
    default: 1

  sitekit.pages.termsAndConditions:
    category: Sitekit.pages
    type: page
    default: 1

  sitekit.pages.legalNotice:
    category: Sitekit.pages
    type: page
    default: 1

  sitekit.pages.privacyPolicy:
    category: Sitekit.pages
    type: page
    default: 1

  sitekit.content.contentElementsPageAdvanced:
    label: 'Content Elements for Backend Layout "Advanced"'
    category: Sitekit.templates
    type: string
    default: 'ot-sitekit-base-container-1-col-container,ot-sitekit-base-container-1-col-container-fluid,ot-sitekit-base-container-1-col-bgcolor,ot-sitekit-base-container-1-col-article,ot-sitekit-base-container-1-col-section,html'

  sitekit.content.contentElementsHero:
    label: 'Content Elements in hero section'
    category: Sitekit.templates
    type: string
    default: ' header,ot_heroimage'

  sitekit.content.contentElementsFullWidthContainer:
    label: 'Content Elements in full width container'
    category: Sitekit.templates
    type: string
    default: 'header,text,menu_subpages,div,felogin_login,form_formframework,list,container,otfaq_list,otjobs_list,otjobs_show,ot_cefluidtemplates,ot_sitekitceimgtextoverlay,ot_sitekitcetexticon,ot_sitekitcetextmedia,ot-sitekit-base-container-grid-cards,ot-sitekit-base-container-2-cols-50-50,ot-sitekit-base-container-2-cols-33-66,ot-sitekit-base-container-2-cols-66-33,ot-sitekit-base-container-3-cols-33-33-33'

  sitekit.frameworks.frontend.directory:
    category: Sitekit.templates
    description: 'LLL:EXT:ot_sitekitbase/Configuration/Sets/Base/labels.xlf:settings.frameworks.frontend.directory.description'
    type: string
    default: 'Bootstrap5'

  sitekit.gutterSize:
    category: Sitekit.templates
    description: 'LLL:EXT:ot_sitekitbase/Configuration/Sets/Base/labels.xlf:settings.gutterSize.description'
    type: string
    default: 3
    enum:
      0: '0'
      1: '1'
      2: '2'
      3: '3'
      4: '4'
      5: '5'

  sitekit.components.page.mainNavigation:
    category: Sitekit.menus.mainMenu
    description: 'LLL:EXT:ot_sitekitbase/Configuration/Sets/Base/labels.xlf:settings.sitekit.components.page.mainNavigation.description'
    default: 'Default'
    type: string
    enum:
      Default: 'Default'
      Advanced: 'Advanced (WCAG)'

  sitekit.menus.mainMenu.collapsing:
    description: 'LLL:EXT:ot_sitekitbase/Configuration/Sets/Base/labels.xlf:settings.sitekit.menu.mainMenu.collapsing.description'
    category: Sitekit.menus.mainMenu
    type: string
    default: 'lg'
    enum:
      'sm': 'sm'
      'md': 'md'
      'lg': 'lg'
      'xl': 'xl'
      'xxl': 'xxl'

  sitekit.menus.mainMenu.levels:
    description: 'LLL:EXT:ot_sitekitbase/Configuration/Sets/Base/labels.xlf:settings.sitekit.menus.mainMenu.levels.description'
    category: Sitekit.menus.mainMenu
    type: string
    default: 2
    enum:
      1: 1
      2: 2

  sitekit.menus.mainMenu.includeSpacer:
    description: 'LLL:EXT:ot_sitekitbase/Configuration/Sets/Base/labels.xlf:settings.sitekit.menus.mainMenu.includeSpacer.description'
    category: Sitekit.menus.mainMenu
    type: bool
    default: false

  sitekit.menus.mainMenu.logo.width:
    description: 'LLL:EXT:ot_sitekitbase/Configuration/Sets/Base/labels.xlf:settings.sitekit.menus.mainMenu.logo.width.description'
    category: Sitekit.menus.mainMenu
    type: int
    default: 40

  sitekit.menus.mainMenu.logo.height:
    category: Sitekit.menus.mainMenu
    description: 'LLL:EXT:ot_sitekitbase/Configuration/Sets/Base/labels.xlf:settings.sitekit.menus.mainMenu.logo.height.description'
    type: int
    default: 40


  sitekit.components.page.topMenu:
    category: Sitekit.menus.topMenu
    description: 'LLL:EXT:ot_sitekitbase/Configuration/Sets/Base/labels.xlf:settings.sitekit.components.page.topMenu.description'
    default: 'Default'
    type: string
    enum:
      Default: 'Default'

  sitekit.pages.topMenuRootPage:
    category: Sitekit.menus.topMenu
    description: 'LLL:EXT:ot_sitekitbase/Configuration/Sets/Base/labels.xlf:settings.sitekit.pages.topMenuRootPage.description'
    type: page
    default: 1


  sitekit.menus.languageMenu.enabled:
    category: Sitekit.menus.languageMenu
    description: 'LLL:EXT:ot_sitekitbase/Configuration/Sets/Base/labels.xlf:settings.sitekit.menus.languageMenu.enabled.description'
    type: bool
    default: false

  sitekit.components.page.languageMenu:
    category: Sitekit.menus.languageMenu
    description: 'LLL:EXT:ot_sitekitbase/Configuration/Sets/Base/labels.xlf:settings.sitekit.components.page.languageMenu.description'
    default: 'Default'
    type: string
    enum:
      Default: 'Default'
      Dropdown: 'Dropdown (WCAG)'

  sitekit.menus.languageMenu.dropdownToggle.label.enabled:
    category: Sitekit.menus.languageMenu
    description: 'LLL:EXT:ot_sitekitbase/Configuration/Sets/Base/labels.xlf:settings.sitekit.menus.languageMenu.dropdownToggle.label.enabled.description'
    type: bool
    default: false

  sitekit.menus.subpagesMenu:
    category: Sitekit.menus.subpagesMenu
    description: 'LLL:EXT:ot_sitekitbase/Configuration/Sets/Base/labels.xlf:settings.sitekit.menus.subpagesMenu.description'
    default: 'Default'
    type: string
    enum:
      Default: 'Default'
      Cards: 'Cards (WCAG)'




  sitekit.features.search.enabled:
    category: Sitekit.features.search
    description: 'LLL:EXT:ot_sitekitbase/Configuration/Sets/Base/labels.xlf:settings.sitekit.features.search.enabled.description'
    type: bool
    default: false

  sitekit.features.colorMode.enabled:
    category: Sitekit.features.colorMode
    description: 'LLL:EXT:ot_sitekitbase/Configuration/Sets/Base/labels.xlf:settings.sitekit.features.colorMode.enabled.description'
    type: bool
    default: true

  sitekit.components.page.colorMode:
    category: Sitekit.features.colorMode
    description: 'LLL:EXT:ot_sitekitbase/Configuration/Sets/Base/labels.xlf:settings.sitekit.components.page.colorMode.description'
    default: 'Default'
    type: string
    enum:
      Default: 'Default (WCAG)'

  sitekit.features.colorMode.dropdownToggle.label.enabled:
    category: Sitekit.features.colorMode
    description: 'LLL:EXT:ot_sitekitbase/Configuration/Sets/Base/labels.xlf:settings.sitekit.features.colorMode.dropdownToggle.label.enabled.description'
    type: bool
    default: false



  socialMedia.facebook.account:
    category: SocialMedia.settings
    type: string
    default: ''

  socialMedia.x.account:
    category: SocialMedia.settings
    type: string
    default: ''

  socialMedia.instagram.account:
    category: SocialMedia.settings
    type: string
    default: ''

  socialMedia.linkedIn.account:
    category: SocialMedia.settings
    type: string
    default: ''

  contentElements.menuSubpages.rowCols:
    category: Sitekit.contentElements
    type: string
    default: 'row-cols-1 row-cols-md-2  row-cols-xl-3'
