categories:
  Sitekit:
  Sitekit.project:
    parent: Sitekit
  Sitekit.project.brand:
    parent: Sitekit.project
  SocialMedia.settings:
    parent: Sitekit.project
  Sitekit.pages:
    parent: Sitekit
  Sitekit.templates:
    parent: Sitekit

  Sitekit.menus:
    parent: Sitekit
  Sitekit.menus.main:
    parent: Sitekit.menus
  Sitekit.menus.top:
    parent: Sitekit.menus
  Sitekit.menus.language:
    parent: Sitekit.menus
  Sitekit.menus.footer:
    parent: Sitekit.menus

  Sitekit.features:
    parent: Sitekit
  Sitekit.features.search:
    parent: Sitekit.features
  Sitekit.features.colorModes:
    parent: Sitekit.features

  Sitekit.contentElements:
    parent: Sitekit
  Sitekit.contentElements.menu_subpages:
    parent: Sitekit.contentElements

settings:
  sitekit.project.companyName:
    category: Sitekit.project
    type: string
    default: 'Company Name'

  sitekit.project.companyName2:
    category: Sitekit.project
    type: string
    default: ''

  sitekit.project.addressLine1:
    category: Sitekit.project
    type: string
    default: ''

  sitekit.project.addressLine2:
    category: Sitekit.project
    type: string
    default: ''

  sitekit.project.postalCode:
    category: Sitekit.project
    type: string
    default: ''

  sitekit.project.city:
    category: Sitekit.project
    type: string
    default: ''

  sitekit.project.telephone:
    category: Sitekit.project
    type: string
    default: ''

  sitekit.project.email:
    category: Sitekit.project
    type: string
    default: ''

  sitekit.project.brand.logo.file.svg:
    category: Sitekit.project.brand
    type: string
    default: 'EXT:ot_sitekitbase/Resources/Public/Icons/Extension.svg'

  sitekit.pages.termsAndConditions:
    category: Sitekit.pages
    type: page
    default: 0

  sitekit.pages.legalNotice:
    category: Sitekit.pages
    type: page
    default: 0

  sitekit.pages.privacyPolicy:
    category: Sitekit.pages
    type: page
    default: 0

  sitekit.frameworks.frontend.directory:
    category: Sitekit.templates
    type: string
    default: 'Bootstrap5'

  sitekit.layout.pageHeader.variant:
    category: Sitekit.templates
    type: string
    default: 'TwoRowMenuTop'
    enum:
      TwoRowMenuTop: 'Row 1: Menu Top | Row 2: Logo, Menu Main, Search'
      TwoRowLogoTop: 'Row 1: Logo, Menu Top | Row 2: Menu Main, Search'
#      TwoRowMenuTop: 'LLL:EXT:ot_sitekitbase/Configuration/Sets/Base/labels.xlf:settings.sitekit.layout.pageHeader.variant.TwoRowMenuTop'
#      TwoRowLogoTop: 'LLL:EXT:ot_sitekitbase/Configuration/Sets/Base/labels.xlf:settings.sitekit.layout.pageHeader.variant.TwoRowLogoTop'

#  sitekit.layout.pageFooter.variant:
#    category: Sitekit.templates
#    type: string
#    default: 1
#    enum:
#      1: '1'
#      2: '2'

  sitekit.layout.gutterSize:
    category: Sitekit.templates
    type: string
    default: 3
    enum:
      0: '0'
      1: '1'
      2: '2'
      3: '3'
      4: '4'
      5: '5'

  sitekit.layout.radius:
    category: Sitekit.templates
    type: string
    default: 2
    enum:
      0: '0'
      1: '1'
      2: '2'
      3: '3'
      4: '4'
      5: '5'

  # Main Navigation
  sitekit.menus.main.rootPage:
    category: Sitekit.menus.main
    type: page
    default: 1

  sitekit.menus.main.variant:
    category: Sitekit.menus.main
    type: string
    default: 'Default'
    enum:
      Default: 'Default'
      Advanced: 'Advanced (WCAG)'

  sitekit.menus.main.toggler.variant:
    category: Sitekit.menus.main
    type: string
    default: 'Default'
    enum:
      Default: 'Default'
      Animated: 'Animated (3 lines → X)'

  sitekit.menus.main.navBrand:
    category: Sitekit.menus.main
    type: string
    default: 'Default'
    enum:
      Default: 'Default (Logo + Company Name)'
      HomeIcon: 'Home Icon'
      None: 'None'

  sitekit.menus.main.backgroundColor:
    category: Sitekit.menus.main
    type: string
    default: 'navbar-light'
    enum:
      navbar-light: 'Light Background (navbar-light)'
      navbar-dark: 'Dark Background (navbar-dark)'

  sitekit.menus.main.collapsing:
    category: Sitekit.menus.main
    type: string
    default: 'lg'
    enum:
      'sm': 'sm'
      'md': 'md'
      'lg': 'lg'
      'xl': 'xl'
      'xxl': 'xxl'

  sitekit.menus.main.alignment:
    category: Sitekit.menus.main
    type: string
    default: 'right'
    enum:
      'start': 'Left / Start'
      'center': 'Center'
      'end': 'Right / End'

  sitekit.menus.main.levels:
    category: Sitekit.menus.main
    type: string
    default: 2
    enum:
      1: 1
      2: 2

  sitekit.menus.main.includeSpacer:
    category: Sitekit.menus.main
    type: bool
    default: false

  sitekit.menus.main.logo.width:
    category: Sitekit.menus.main
    type: int
    default: 40

  sitekit.menus.main.logo.height:
    category: Sitekit.menus.main
    type: int
    default: 40

  # Top Navigation
  sitekit.menus.top.rootPage:
    category: Sitekit.menus.top
    type: page
    default: 0

  sitekit.menus.top.variant:
    category: Sitekit.menus.top
    type: string
    default: 'Default'
    enum:
      Default: 'Default'

  # Language Navigation
  sitekit.menus.language.enabled:
    category: Sitekit.menus.language
    type: bool
    default: false

  sitekit.menus.language.variant:
    category: Sitekit.menus.language
    type: string
    default: 'Default'
    enum:
      Default: 'Default'
      Dropdown: 'Dropdown (WCAG)'

  sitekit.menus.language.dropdownToggle.label.enabled:
    category: Sitekit.menus.language
    type: bool
    default: false

  # Footer Navigation
  sitekit.menus.footer.rootPage:
    category: Sitekit.menus.footer
    type: page
    default: 0

  sitekit.features.search.enabled:
    category: Sitekit.features.search
    type: bool
    default: false

  sitekit.features.colorModes.enabled:
    category: Sitekit.features.colorModes
    type: bool
    default: true

  sitekit.features.colorModes.variant:
    category: Sitekit.features.colorModes
    default: 'Default'
    type: string
    enum:
      Default: 'Default (WCAG)'

  sitekit.features.colorModes.dropdownToggle.label.enabled:
    category: Sitekit.features.colorModes
    type: bool
    default: false


  sitekit.project.socialMedia.facebook.account:
    category: SocialMedia.settings
    type: string
    default: ''

  sitekit.project.socialMedia.x.account:
    category: SocialMedia.settings
    type: string
    default: ''

  sitekit.project.socialMedia.instagram.account:
    category: SocialMedia.settings
    type: string
    default: ''

  sitekit.project.socialMedia.linkedIn.account:
    category: SocialMedia.settings
    type: string
    default: ''

  # Subpages Navigation
  sitekit.contentElements.menu_subpages.variant:
    category: Sitekit.contentElements.menu_subpages
    type: string
    default: 'Default'
    enum:
      Default: 'Default'
      Cards: 'Cards (WCAG)'

  sitekit.contentElements.menu_subpages.rowCols:
    category: Sitekit.contentElements.menu_subpages
    type: string
    default: 'row-cols-1 row-cols-md-2 row-cols-xl-3'
