categories:
  Sitekit:
    label: 'Sitekit'
  Sitekit.brand:
    label: 'Brand'
    parent: Sitekit
  Sitekit.project:
    label: 'Project'
    parent: Sitekit
  Sitekit.pages:
    label: 'Pages'
    parent: Sitekit
  Sitekit.templates:
    label: 'Templates'
    parent: Sitekit
  Sitekit.menus:
    label: 'Menus'
    parent: Sitekit
  Sitekit.menus.mainMenu:
    label: 'MainMenu'
    parent: Sitekit.menus
  Sitekit.menus.topMenu:
    label: 'TopMenu'
    parent: Sitekit.menus
  Sitekit.menus.topMenu.colorMode:
    label: 'Color Mode'
    parent: Sitekit.menus.topMenu
  Sitekit.search:
    label: 'Search'
    parent: Sitekit
  SocialMedia.settings:
    label: 'Social Media'
    parent: Sitekit

settings:
  sitekit.brand.logo:
    label: 'Logo'
    category: Sitekit.brand
    description: 'e.g. EXT:ot_sitekitbase/Resources/Public/Icons/Extension.svg'
    type: string
    default: 'EXT:ot_sitekitbase/Resources/Public/Icons/Extension.svg'

  sitekit.project.companyName:
    label: 'Company Name'
    category: Sitekit.project
    description: 'The name of the company will be used in the Navbar, Footer, ….'
    type: string
    default: 'Company Name'

  sitekit.project.addressLine1:
    label: 'Address Line 1'
    category: Sitekit.project
    description: 'Street and House number'
    type: string
    default: ''

  sitekit.project.addressLine2:
    label: 'Address Line 2'
    category: Sitekit.project
    description: 'Additional address information'
    type: string
    default: ''

  sitekit.project.postalCode:
    label: 'Postal Code'
    category: Sitekit.project
    type: string
    default: ''

  sitekit.project.city:
    label: 'City'
    category: Sitekit.project
    type: string
    default: ''

  sitekit.pages.root:
    label: 'Root Page Id'
    category: Sitekit.pages
    description: 'The root page id for this website. It is the parent page id of the main navigation.'
    type: int
    default: 1

  sitekit.pages.termsAndConditions:
    label: 'Terms and conditions'
    category: Sitekit.pages
    type: int
    default: 0

  sitekit.pages.legalDisclosure:
    label: 'Legal Disclosure'
    category: Sitekit.pages
    type: int
    default: 0

  sitekit.pages.privacyPolicy:
    label: 'Privacy Policy'
    category: Sitekit.pages
    type: int
    default: 0

  sitekit.menus.mainMenu.collapsing:
    label: 'Responsive Collapsing'
    category: Sitekit.menus.mainMenu
    description: 'Navbars require a wrapping .navbar with .navbar-expand{-sm|-md|-lg|-xl|-xxl} for responsive collapsing.'
    type: string
    default: 'lg'
    enum:
      'sm': 'sm'
      'md': 'md'
      'lg': 'lg'
      'xl': 'xl'
      'xxl': 'xxl'

  sitekit.menus.mainMenu.levels:
    label: 'Levels'
    category: Sitekit.menus.mainMenu
    description: ''
    type: string
    default: 2
    enum:
      1: 1
      2: 2

  sitekit.menus.mainMenu.includeSpacer:
    label: 'Include Spacer'
    category: Sitekit.menus.mainMenu
    description: ''
    type: bool
    default: false

  sitekit.menus.topMenu.colorMode.enabled:
    label: 'Enabled'
    category: Sitekit.menus.topMenu.colorMode
    description: ''
    type: bool
    default: true

  sitekit.menus.mainMenu.logo.width:
    label: 'Logo Width'
    category: Sitekit.menus.mainMenu
    description: 'Width in Pixels, e.g. {40} for 40px.'
    type: int
    default: 40

  sitekit.menus.mainMenu.logo.height:
    label: 'Logo Height'
    category: Sitekit.menus.mainMenu
    description: 'Height in Pixels, e.g. {40} for 40px.'
    type: int
    default: 40

  sitekit.search.enabled:
    label: 'Enabled'
    category: Sitekit.search
    description: 'Enables parts of the search in the frontend.'
    type: bool
    default: false

  sitekit.frameworks.frontend.directory:
    label: 'Frontend Framework Directory'
    category: Sitekit.templates
    description: 'Parent directory to templates files. This path is also used by many content elements.'
    type: string
    default: 'Bootstrap5'

  sitekit.defaultGutterSize:
    label: 'Gutter Size'
    category: Sitekit.templates
    description: 'THe default gutter size (e.g. for card decks)'
    type: string
    default: 3
    enum:
      0: '0'
      1: '1'
      2: '2'
      3: '3'
      4: '4'
      5: '5'

  socialMedia.facebook.account:
    label: 'Facebook Account'
    category: SocialMedia.settings
    description: 'Name of the Facebook Account'
    type: string
    default: ''

  socialMedia.x.account:
    label: 'X/Twitter Account'
    category: SocialMedia.settings
    description: 'Name of the X/Twitter Account'
    type: string
    default: ''

  socialMedia.instagram.account:
    label: 'Instagram Account'
    category: SocialMedia.settings
    description: 'Name of the Instagram Account'
    type: string
    default: ''

  socialMedia.linkedIn.account:
    label: 'LinkedIn Account'
    category: SocialMedia.settings
    description: 'Name of the LinkedIn Account'
    type: string
    default: ''
