name: oliverthiele/ot-sitekit-base-content-elements
label: Content Element import
dependencies:
  - oliverthiele/ot-sitekit-base
  - oliverthiele/ot-heroimage
  - oliverthiele/ot-sitekit-ce-textmedia
  - oliverthiele/ot-sitekit-ce-imgtextoverlay
  - oliverthiele/ot-sitekit-ce-texticon
  - oliverthiele/ot-irrebuttons
